In [1]:
import torch
import torch.nn as nn

In [2]:
torch.manual_seed(42)    # now it make the weights and bias initialization reproducible

In [3]:
inputs = torch.tensor([1.0, 2.0, 3.0])
inputs

tensor([1., 2., 3.])

In [4]:
neuron = nn.Linear(in_features=3, out_features=1)   # creates a neuron capable of calculating the Weighted Sum
neuron

Linear(in_features=3, out_features=1, bias=True)

In [5]:
print("Weights : ",neuron.weight)
print(f"Bias : {neuron.bias}")

Weights :  Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)
Bias : Parameter containing:
tensor([0.5304], requires_grad=True)


In [6]:
output = neuron(inputs)
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [7]:
print("verify by input*weight + bias")
print(neuron.weight@inputs + neuron.bias)

verify by input*weight + bias
tensor([1.5244], grad_fn=<AddBackward0>)
