In [1]:
import numpy as np


In [2]:
arr1 =np.array([1,2,3,4,5])

In [3]:
print(arr1)

[1 2 3 4 5]


## Properties of Numpy
- Numpy are are faster as they are optimised in C
- Numpy store data in continuous memory block
- Uses less memory (optimised storage)
- Built in Mathematical Functions
- Supports direct vectorised operations (operation execute in bulk)

# Time Performace comparision


In [4]:
import time
size = 10_000_000
py_list = list(range(size))  # creates a list of specified range

start1 = time.time()
sq_list = [val**2 for val in py_list]    # list comprehension has expression in beginning
end1 = time.time()
print(f"Total time for Squaring Python List is : {end1-start1}")

np_arr = np.array(py_list)  # its takse a parameter list and converts it into array capable of vectorization
start2 = time.time()
sq_arr = np_arr ** 2 
end2 = time.time()
print(f"Total time for Squaring Numpy Array is : {end2-start2}")

Total time for Squaring Python List is : 7.049709796905518
Total time for Squaring Numpy Array is : 0.19927597045898438


# Space Peformance Comparision

In [5]:
import sys

list_size = sys.getsizeof(py_list) 
elements_size = sum(sys.getsizeof(x) for x in py_list)
total_size = list_size + elements_size
print(f"Size of py_list is : {total_size}")

print(f"Size of nb_array is : {np_arr.nbytes}")

Size of py_list is : 3600000056
Size of nb_array is : 800000000


## Numpy Properties
- np_arr.dtype : returns the data type of list elements
- np_arr.shape : returns the dimentions of the array (if 1-D then returns the number of elements)

In [6]:
arr1 =np.array([1,2,3,4,5, "Prime"])
print(arr1)
print(f"Type is {arr1.dtype} And Shape : {arr1.shape} ")

['1' '2' '3' '4' '5' 'Prime']
Type is <U21 And Shape : (6,) 


## Creating 1-D Array : 
- np.zeros(), np.ones() :is used to create a array
- zeros((row, col) dtype="type") : (r, c) is used to define the shape and dtype is used to define the datatype of each element
- by default the type is floating
- (row,) : is used to define One-Dimentional array
- np.full() :   custom PRRFILL is dine using  : np.full((r,c), value)   -> value becomes the each element of array
- np.eye(size) :  Creates a identity matrics of specified size
- np.arange(start, end, step) : creates a 1-D Array of range form start to one less than end and for each element at the specified step
- np.linspace(start, end, count_of_elements) : creates a evenly space array of specified could between the specifiedn start and end range
  

In [16]:
# zeros((row, col) dtype="type") : (r, c) is used to define the shape and dtype is used to define the datatype of each element
arr_zeros = np.zeros((2,3), dtype="int64")    # np.zeros(), np.ones() :is used to create a array
print(arr_zeros)
print(f"The dtype is : {arr_zeros.dtype} And the Shape is : {arr_zeros.shape}")


[[0 0 0]
 [0 0 0]]
The dtype is : int64 And the Shape is : (2, 3)


In [17]:
arr_ones = np.ones((5,))    # by default the type is floating And (row,) : is used to define One-Dimentional array 
print(arr_ones)

[1. 1. 1. 1. 1.]


In [15]:
arr_full = np.full((3,4), 101)    # np.full((r,c), value)   -> value becomes the each element of array
print(arr_full)

[[101 101 101 101]
 [101 101 101 101]
 [101 101 101 101]]


In [24]:
arr_eye = np.eye(3, dtype="int64")   # np.eye(size) : Creates a identity matrics of specified size
print(arr_eye)
print(f"Array Shape is : {arr_eye.shape}")


[[1 0 0]
 [0 1 0]
 [0 0 1]]
Array Shape is : (3, 3)


In [26]:
# arange(start, end, step) : creates a 1-D Array of range form start to one less than end and for each element at the specified step 
arr_arange = np.arange(3, 25, 2)
print(arr_arange)
print(f"Array Shape is : {arr_arange.shape}")

[ 3  5  7  9 11 13 15 17 19 21 23]
Array Shape is : (11,)


In [30]:
 # np.linspace(start, end, count_of_elements) : creates a evenly space array of specified could between the specifiedn start and end range
arr_linspace = np.linspace(1,100,4, dtype="int64")
print(arr_linspace)
print(arr_linspace.shape)

[  1  34  67 100]
(4,)


## Array Properties
- arr.size : returns the count of total elements in the array
- arr.ndim : return the dimension of the array
- arr.astype(np.datatype) : converts the array of one type to other type
- arr.copy() : creates the copy of array

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   # to create np array we pass litst in np.array()
print(arr)
print(f"Array was of type {arr.dtype}")
float_arr = arr.astype(np.float64)
print(float_arr)
print(f"Array was of type {float_arr.dtype}")




[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array was of type int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Array was of type float64


## Operations Of Array 
- arr.reshape((row, col)) : is used to reshape the array
- arr.flattened() : is used to convert an array in 1-D Array

In [44]:
arr = np.array([[1,2,3], [6,7,8]])
print(arr)
print(f"Shape of Array is : {arr.shape}")

re_arr = arr.reshape((3,2))     # arr.reshape((row, col)) : is used to reshape the array
print(re_arr)
print(f"Shape of Array is : {re_arr.shape}")

arr_flat = arr.flatten()     # arr.flattened() : is used to convert an array in 1-D Array
print(arr_flat)
print(f"Shape of Array is : {arr_flat.shape}")

[[1 2 3]
 [6 7 8]]
Shape of Array is : (2, 3)
[[1 2]
 [3 6]
 [7 8]]
Shape of Array is : (3, 2)
[1 2 3 6 7 8]
Shape of Array is : (6,)


## Indexing
- Slicing : arr[start, end, step] -> it returns the data from start index to one less than end index skiping element in accordance with 'step'.
  list slicing creates a copy(changes do not impact original) of sub array  but numpy slicing creates a view(changes do impact original) for the array
- fancy indexing : is the technique in which index's array is passed in array index's
  For ex : arr[[1,3,6]] will return the at the index 1, 3 and 6
- boolean indexing : in place of index we could pass a boolean condition and those index satisfing the condtion will have thier value returned
  

In [52]:
arr = np.array([21,4,7,9,12,445,123])
print(arr[::3])   # print first to last element with 3 intervals(ignores 2 element in between)

idx = [1,2,4]
print(arr[idx])   # fancy indexing : set of indexes are passed and corresponding values are returned

print(arr[arr > 5])     # returns value creater than the specified value
print(arr[arr%2 == 0])   # return even values only

[ 21   9 123]
[ 4  7 12]
[ 21   7   9  12 445 123]
[ 4 12]
