## Data Type
- int32, int64
- float32, float64
- bool
- complex64, complex128
- String : S(byte-str)  And U(unicode-str)

In [11]:
import numpy as np
cx = np.array(5.0 + 8.5j)  # complex DataType
cy = np.array(2.0 + 7.4j)
print(cx)
print(cx.dtype)
print(f"The sum of two complex number is : {cx+cy}")

(5+8.5j)
complex128
The sum of two complex number is : (7+15.9j)


# MultiDimentional Array
## 3-D Array
- axis 0 : represents the depth or the layers
- axis 1 : represents the row in each layer
- axis 2 : represents the column in each layer

## Axis wise operation
- np.sum(arr)  : is used to calcualte the sum of all element
- np.sum(arr, axis=0) : is used to calculate the sum of individual columns(in form of 1-D array)
- np.sum(arr, axis=1) : is used to calculate the sum of individual rows(in form of 1-D array)

## Slicing
- arr_name[row_start:row_end, column_start:column_end] note it slice one less than the end 

In [18]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)
sum_matrix = np.sum(matrix)
print(f"Sum of all elements if matrix is : {sum_matrix}")
sum_of_columns = np.sum(matrix, axis=0)
print(f"Sum of all columns if matrix is : {sum_of_columns}") # np.sum(arr, axis=0) : is used to calculate the sum of individual columns
sum_of_rows = np.sum(matrix, axis=1)
print(f"Sum of all rows if matrix is : {sum_of_rows}") # is used to calculate the sum of individual rows
print("Matrix After Slicing is : ")
print(matrix[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements if matrix is : 45
Sum of all columns if matrix is : [12 15 18]
Sum of all rows if matrix is : [ 6 15 24]
Matrix After Slicing is : 
[[2]
 [5]]


In [32]:
# Slicing in 3-D Array 
arr3D = np.array([ [[1,2],[3,4],[5,6]], [[7,8],[10,11],[13,14]] ])
print(arr3D)
print("First Column of both matrix : ")
print(arr3D[:,:,0])
print("First Row of both matrix : ")
print(arr3D[:,1,:])
print("Manipulating second row with 1 : ")
arr3D[:,1,:] = 99    # slicing in numpy creates view so changes cause change in collection too.
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [10 11]
  [13 14]]]
First Column of both matrix : 
[[ 1  3  5]
 [ 7 10 13]]
First Row of both matrix : 
[[ 3  4]
 [10 11]]
Manipulating second row with 1 : 
[[[ 1  2]
  [99 99]
  [ 5  6]]

 [[ 7  8]
  [99 99]
  [13 14]]]
