## Data Type
- int32, int64
- float32, float64
- bool
- complex64, complex128
- String : S(byte-str)  And U(unicode-str)

In [1]:
import numpy as np
cx = np.array(5.0 + 8.5j)  # complex DataType
cy = np.array(2.0 + 7.4j)
print(cx)
print(cx.dtype)
print(f"The sum of two complex number is : {cx+cy}")

(5+8.5j)
complex128
The sum of two complex number is : (7+15.9j)


# MultiDimentional Array
## 3-D Array
- axis 0 : represents the depth or the layers
- axis 1 : represents the row in each layer
- axis 2 : represents the column in each layer

## Axis wise operation
- np.sum(arr)  : is used to calcualte the sum of all element
- np.sum(arr, axis=0) : is used to calculate the sum of individual columns(in form of 1-D array)
- np.sum(arr, axis=1) : is used to calculate the sum of individual rows(in form of 1-D array)

## Slicing
- arr_name[row_start:row_end, column_start:column_end] note it slice one less than the end 

In [2]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)
sum_matrix = np.sum(matrix)
print(f"Sum of all elements if matrix is : {sum_matrix}")
sum_of_columns = np.sum(matrix, axis=0)
print(f"Sum of all columns if matrix is : {sum_of_columns}") # np.sum(arr, axis=0) : is used to calculate the sum of individual columns
sum_of_rows = np.sum(matrix, axis=1)
print(f"Sum of all rows if matrix is : {sum_of_rows}") # is used to calculate the sum of individual rows
print("Matrix After Slicing is : ")
print(matrix[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements if matrix is : 45
Sum of all columns if matrix is : [12 15 18]
Sum of all rows if matrix is : [ 6 15 24]
Matrix After Slicing is : 
[[2]
 [5]]


In [3]:
# Slicing in 3-D Array 
arr3D = np.array([ [[1,2],[3,4],[5,6]], [[7,8],[10,11],[13,14]] ])
print(arr3D)
print("First Column of both matrix : ")
print(arr3D[:,:,0])
print("First Row of both matrix : ")
print(arr3D[:,1,:])
print("Manipulating second row with 1 : ")
arr3D[:,1,:] = 99    # slicing in numpy creates view so changes cause change in collection too.
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [10 11]
  [13 14]]]
First Column of both matrix : 
[[ 1  3  5]
 [ 7 10 13]]
First Row of both matrix : 
[[ 3  4]
 [10 11]]
Manipulating second row with 1 : 
[[[ 1  2]
  [99 99]
  [ 5  6]]

 [[ 7  8]
  [99 99]
  [13 14]]]


## Vectorization
- Vectorization as operations execute in bulk to entire array (not individually elements through loops)
  
## BroadCasting
- BroadCasting : Methodology of stretching of array to make it compatible for operation with other array.
  Condition : Either row/column should be one or equal to that of the other array


In [4]:
arr = np.array([1,2,3,4,5])
print(arr ** 2)   # Vectorization as operations execute in bulk to entire array (not individually elements through loops)
other_arr = np.array([[1,2,3,4,5], [10,11,12,13,14]])   
print(arr + other_arr) # Broadcasting  takes place by streching the shorter array of dimention of 1 row to 2 rows to make it compatible for operations.

[ 1  4  9 16 25]
[[ 2  4  6  8 10]
 [11 13 15 17 19]]


# Normalization
## Fomula :     [ (arr - mean) / std_dev ]  
- np.mean(array)  :  [ sigma(val_i)/ N ]    -> Mean of Array
- np.std(array)  :  [ sqrt(sigma{(val_i - mean)^2)}/N ]   ->  STD Deviation of Array
  
# Properties of Normalized Array :
- Mean = 0
- Standard Deviation == 1 (approx.)


In [8]:
arr = [[1,2], [3,4]]
print("Original Array : ")
print(arr)
mean = np.mean(arr)
print(f"Mean of the array is  : {mean}")
std_dev = np.std(arr)
print(f"Standard Deviation of the array is  : {std_dev}")
normalized_array = (arr-mean)/std_dev
print("Normalized Array is  : ")
print(normalized_array)
nor_mean = np.mean(normalized_array)
print(f"Mean of the Normalized array is  : {nor_mean}")      # Normalized Mean = 0 
nor_std_dev = np.std(normalized_array)
print(f"Standard Deviation of the Normalized array is  : {nor_std_dev}")  # Normalized Standard Deviation = 1

Original Array : 
[[1, 2], [3, 4]]
Mean of the array is  : 2.5
Standard Deviation of the array is  : 1.118033988749895
Normalized Array is  : 
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
Mean of the Normalized array is  : 0.0
Standard Deviation of the Normalized array is  : 1.0
